import {writable} from 'svelte/store';

export const CharacterStore = writable([
    {"id":0,"name":"Uzumaki Naruto","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No", "skill_effects":["Stun",
    "Healer"]},
    {"id":1,"name":"Uchiha Sasuke","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No", "skill_effects":["Paralyze",
    "Unable to Reduce Damage/Invuln"]},
    {"id":2,"name":"Haruno Sakura","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Stun",
    "Healer"]},
    {"id":3,"name":"Inuzuka Kiba","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Unable to Reduce Damage/Invuln",
    "AoE Offensive"]},
    {"id":4,"name":"Aburame Shino","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Chakra Drain",
    "AoE Defensive"]},
    {"id":5,"name":"Hyuga Hinata","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Chakra Drain",
    "Paralyze"]},
    {"id":6,"name":"Hyuga Neji","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Ignore DD",
    "Chakra Drain",
    "AoE Offensive"]},
    {"id":7,"name":"Rock Lee","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Destroy DD"]},
    {"id":8,"name":"Tenten","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":9,"name":"Nara Shikamaru","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":10,"name":"Akimichi Chouji","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":11,"name":"Yamanaka Ino","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":12,"name":"Young Yahiko","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[ "Unable to Reduce Damage/Invuln",
    "Ignore DD"]},
    {"id":13,"name":"Young Nagato","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Stun",
    "AoE Offensive"]},
    {"id":14,"name":"Young Konan","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":15,"name":"Young Kakashi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":16,"name":"Young Obito","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction"]},
    {"id":17,"name":"Nohara Rin","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":[ "Healer",
    "Ignore DD"]},
    {"id":18,"name":"Hyuga Hanabi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":19,"name":"Umino Iruka","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":20,"name":"Mizuki","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":21,"name":"Demon Brothers","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":22,"name":"Waraji And Zori","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Stun",
    "Reflect"]},
    {"id":23,"name":"Yuki Haku","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Stun"]},
    {"id":24,"name":"Momochi Zabuza","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun",
    "Chakra Increase"]},
    {"id":25,"name":"Oboro","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":[ "AoE Offensive",
    "Stun"]},
    {"id":26,"name":"Mubi","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":27,"name":"Kagari","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer"]},
    {"id":28,"name":"Shigure","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Counter"]},
    {"id":29,"name":"Gaara","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":30,"name":"Kankuro","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":31,"name":"Temari","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive"]},
    {"id":32,"name":"Kinuta Dosu","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[        "Unable to Reduce Damage/Invuln"
]},
    {"id":33,"name":"Abumi Zaku","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Counter"]},
    {"id":34,"name":"Tshuchi Kin","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[      "Chakra Drain",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":35,"name":"Akado Yoroi","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain"]},
    {"id":36,"name":"Tsurugi Misumi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":[ "Reflect",
    "Stun"]},
    {"id":37,"name":"Spy Kabuto","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Drain"]},
    {"id":38,"name":"Mitarashi Anko","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Unable to Reduce Damage/Invuln"]},
    {"id":39,"name":"Shiore","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Chakra Increase",
    "Healer",
    "Stun"]},
    {"id":40,"name":"Young Karin","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Healer",
    "Ignore DD",
    "Unable to Reduce Damage/Invuln"]},
    {"id":41,"name":"First Stage Cursed Seal Sasuke","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":42,"name":"Ebisu","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Reflect",
    "Stun"]},
    {"id":43,"name":"Shiranui Genma","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":44,"name":"Hayate Gekko","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":45,"name":"Baki","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed"]},
    {"id":46,"name":"Shukaku Gaara","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":47,"name":"Tayuya","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":[ "Affliction",
    "AoE Offensive",
    "Chakra Drain",
    "Stun"]},
    {"id":48,"name":"Kidomaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Counter"]},
    {"id":49,"name":"Sakon And Ukon","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Healer"]},
    {"id":50,"name":"Jirobo","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Chakra Drain"]},
    {"id":51,"name":"Kimimaro","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":52,"name":"Cursed Seal Tayuya","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Paralyze"]},
    {"id":53,"name":"Cursed Seal Kidomaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Paralyze"]},
    {"id":54,"name":"Cursed Seal Sakon and Ukon","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer"]},
    {"id":55,"name":"Cursed Seal Jirobo","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain"]},
    {"id":56,"name":"Cursed Seal Kimimaro","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Stun"]},
    {"id":57,"name":"Butterfly Chouji","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[ "AoE Defensive",
    "Stun"]},
    {"id":58,"name":"Rehabilitated Gaara","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Chakra Increase",
    "Destroy DD"]},
    {"id":59,"name":"Drunken Lee","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Destroy DD"]},
    {"id":60,"name":"Kyubi Naruto","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer",
    "Stun"]},
    {"id":61,"name":"Second Stage Cursed Seal Sasuke","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":62,"name":"ANBU Kakashi","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[  "AoE Defensive",
    "Chakra Drain",
    "Stun"]},
    {"id":63,"name":"ANBU Itachi","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter"]},
    {"id":64,"name":"ANBU Kinoe","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Ignore Helpful Effects"]},
    {"id":65,"name":"ANBU Yugao","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":66,"name":"Nara Shikaku","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":67,"name":"Akimichi Choza","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive"]},
    {"id":68,"name":"Yamanaka Inoichi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Reflect",
    "Stun"]},
    {"id":69,"name":"Hatake Kakashi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Reflect",
    "Stun"]},
    {"id":70,"name":"Maito Gai","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":71,"name":"Yuhi Kurenai","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Increase",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":72,"name":"Sarutobi Asuma","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive/Defensive",
    "Reflect"]},
    {"id":73,"name":"Uchiha Itachi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":74,"name":"Hoshigaki Kisame","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain",
    "Stun"]},
    {"id":75,"name":"Shizune","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Healer"]},
    {"id":76,"name":"Yakushi Kabuto","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Chakra Increase",
    "Healer",
    "Stun"]},
    {"id":77,"name":"Jiraiya","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Unable to Reduce Damage/Invuln"]},
    {"id":78,"name":"Tsunade","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Healer",
    "Stun"]},
    {"id":79,"name":"Orochimaru","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD",
    "Stun"]},
    {"id":80,"name":"Kakko","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":81,"name":"Mahiru","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Ignore Damage Reduction"]},
    {"id":82,"name":"Taiseki","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":83,"name":"Guruguru Obito","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Healer"]},
    {"id":84,"name":"Namikaze Minato","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Unable to Reduce Damage/Invuln"]},
    {"id":85,"name":"Uzumaki Kushina","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Stun"]},
    {"id":86,"name":"Maito Dai","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Support Character"]},
    {"id":87,"name":"Uchiha Fugaku","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Support Character"]},
    {"id":88,"name":"Renegade Orochimaru","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":[ "Healer",
    "Stun"]},
    {"id":89,"name":"Akatsuki Orochimaru","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Support Character"]},
    {"id":90,"name":"Young Kushina","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":91,"name":"Young Minato","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Paralyze"]},
    {"id":92,"name":"Edo Tensei Senju Hashirama","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Chakra Increase",
    "Stun"]},
    {"id":93,"name":"Edo Tensei Senju Tobirama","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Ignore Helpful",
    "Stun"]},
    {"id":94,"name":"Sarutobi Hiruzen","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Stun"]},
    {"id":95,"name":"Yondaime Minato","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "Reflect"]},
    {"id":96,"name":"Masked Man","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":97,"name":"Senju Tobirama","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Counter"]},
    {"id":98,"name":"Uchiha Izuna","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":99,"name":"Senju Hashirama","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":100,"name":"Uchiha Madara","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":101,"name":"Senju Butsuma","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":102,"name":"Uchiha Tajima","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":103,"name":"Young Hashirama","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":104,"name":"Young Madara","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":105,"name":"Uchiha Naka","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":106,"name":"Uchiha Naori","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Chakra Increase",
    "Reflect"]},
    {"id":107,"name":"Uzumaki Naruto S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Stun"]},
    {"id":108,"name":"Haruno Sakura S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer"]},
    {"id":109,"name":"Sai S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Stun"]},
    {"id":110,"name":"Inuzuka Kiba S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":111,"name":"Aburame Shino S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "Chakra Drain",
    "Counter"]},
    {"id":112,"name":"Hyuga Hinata S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain",
    "Chakra Increase"]},
    {"id":113,"name":"Hyuga Neji S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Chakra Drain",
    "Counter",
    "Destroy DD",
    "Unable to Reduce Damage/Invu"]},
    {"id":114,"name":"Rock Lee S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":115,"name":"Tenten S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Reflect"]},
    {"id":116,"name":"Nara Shikamaru S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":117,"name":"Akimichi Chouji S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Stun"]},
    {"id":118,"name":"Yamanaka Ino S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive/Defensive",
    "Counter",
    "Ignore DD",
    "Stun",
    "Unable to Reduce Damage"]},
    {"id":119,"name":"Hatake Kakashi S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Chakra Increase",
    "Stun"]},
    {"id":120,"name":"Yamato S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Ignore Friendly Effects",
    "Stun"]},
    {"id":121,"name":"Maito Gai S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":122,"name":"Sarutobi Asuma S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":123,"name":"Kazekage Gaara S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Stun"]},
    {"id":124,"name":"Kankuro S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Defensive",
    "Counter"]},
    {"id":125,"name":"Temari S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":126,"name":"Chiyo S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer"]},
    {"id":127,"name":"Hiruko S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Affliction"]},
    {"id":128,"name":"Deidara S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":129,"name":"Itachi Body Double S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter/Reflect"]},
    {"id":130,"name":"Kisame Body Double S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Stun"]},
    {"id":131,"name":"Sasori of the Red Sand S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":132,"name":"Puppet Sasori S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":133,"name":"Yakushi Kabuto S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Paralyze",
    "Stun"]},
    {"id":134,"name":"Orochimaru S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Healer",
    "Stun"]},
    {"id":135,"name":"Kyubi Naruto S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Unable to reduce damage/Invuln"]},
    {"id":136,"name":"Uchiha Sasuke S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Bleed",
    "Stun"]},
    {"id":137,"name":"Biwa Juzo","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Destroy DD"]},
    {"id":138,"name":"Yondaime Yagura","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Ignore DD",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":139,"name":"Sora S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Drain"]},
    {"id":140,"name":"Fuka S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Paralyze"]},
    {"id":141,"name":"Fudo S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD",
    "Stun",
    "AoE Offensive"]},
    {"id":142,"name":"Fuen S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":143,"name":"Kazuma S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Bleed",
    "Stun"]},
    {"id":144,"name":"Nii Yugito S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":145,"name":"Hidan S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed"]},
    {"id":146,"name":"Kakuzu S","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Drain",
    "Healer",
    "Paralyze",
    "Stun"]},
    {"id":147,"name":"Chiriku S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Unable to Reduce Damage/Invuln",
    "Stun"]},
    {"id":148,"name":"Izumo and Kotetsu S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":149,"name":"Yamashiro Aoba S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive"]},
    {"id":150,"name":"White Snake Orochimaru S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Healer",
    "Paralyze",
    "Stun"]},
    {"id":151,"name":"Uzumaki Karin S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Counter",
    "Healer",
    "Stun"]},
    {"id":152,"name":"Hozuki Suigetsu S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD"]},
    {"id":153,"name":"Jugo S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Stun"]},
    {"id":154,"name":"Roshi S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":155,"name":"Han","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive"]},
    {"id":156,"name":"Fuu S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Healer",
    "Reflect",
    "Stun"]},
    {"id":157,"name":"True Artist Deidara S","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":158,"name":"Cursed Seal Sasuke S","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Drain",
    "Stun"]},
    {"id":159,"name":"Uchiha Itachi S","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"Yes","heal":"Yes","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Drain/Increase",
    "Counter",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":160,"name":"Akatsuki Sasuke S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Paralyze",
    "Stun"]},
    {"id":161,"name":"Killer Bee S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":162,"name":"Uchiha Shisui","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction"]},
    {"id":163,"name":"Yahiko","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Stun"]},
    {"id":164,"name":"Uzumaki Nagato","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Stun"]},
    {"id":165,"name":"Konan","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Chakra Increase"]},
    {"id":166,"name":"Jiraiya S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Reflect",
    "Stun"]},
    {"id":167,"name":"Sage Jiraiya S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":168,"name":"Animal Path Pain S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain",
    "Destroy DD"]},
    {"id":169,"name":"Young Jiraiya","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Unable to Invuln/Heal"]},
    {"id":170,"name":"Young Orochimaru","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Drain",
    "Stun"]},
    {"id":171,"name":"Young Tsunade","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Healer",
    "Paralyze"]},
    {"id":172,"name":"Hanzo of the Salamander","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Reflect",
    "Stun"]},
    {"id":173,"name":"Akatsuki Konan S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":174,"name":"Fukasaku and Shima S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Healer",
    "Stun"]},
    {"id":175,"name":"Nara Shikaku S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive/Defensive",
    "Counter",
    "Stun"]},
    {"id":176,"name":"Akimichi Choza S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Defensive",
    "Counter"]},
    {"id":177,"name":"Yamanaka Inoichi S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer",
    "Stun",
    "Unable to Invuln"]},
    {"id":178,"name":"Inuzuka Tsume S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive"]},
    {"id":179,"name":"Aburame Shibi S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Drain",
    "Destroy/Ignore DD"]},
    {"id":180,"name":"Hyuga Hiashi S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Chakra Drain",
    "Reflect"]},
    {"id":181,"name":"Utakata S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Heal",
    "Remove DD"]},
    {"id":182,"name":"Rokubi Utakata","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Bleed",
    "Reflect",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":183,"name":"Sarutobi Konohamaru S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":184,"name":"Ebisu S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter"]},
    {"id":185,"name":"Morino Ibiki S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":186,"name":"Sage Naruto S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Counter",
    "Destroy DD",
    "Healer",
    "Stun"]},
    {"id":187,"name":"Six Tails Kyubi Naruto S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":188,"name":"Deva Path Pain S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Chakra Increase",
    "Stun"]},
    {"id":189,"name":"Asura Path Pain S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Destroy DD"]},
    {"id":190,"name":"Human Path Pain S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":191,"name":"Female Animal Path Pain S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":192,"name":"Preta Path Pain S","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Chakra Drain",
    "Reflect",
    "Stun"]},
    {"id":193,"name":"Naraka Path Pain S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer",
    "Stun"]},
    {"id":194,"name":"Aburame Torune S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Increase"]},
    {"id":195,"name":"Yamanaka Fu S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":196,"name":"Chojuro S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD"]},
    {"id":197,"name":"Ao S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive/Defensive",
    "Chakra Increase",
    "Counter",
    "Unable to Reduce Damage/Invuln"]},
    {"id":198,"name":"Darui S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Bleed",
    "Paralyze",
    "Stun"]},
    {"id":199,"name":"Cee S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer"]},
    {"id":200,"name":"Akatsuchi S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Chakra Drain"]},
    {"id":201,"name":"Kurotsuchi S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":202,"name":"Cursed Seal Jugo S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":203,"name":"Susanoo Sasuke S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Stun"]},
    {"id":204,"name":"Shimura Danzo S","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Bleed",
    "Counter",
    "Stun"]},
    {"id":205,"name":"Rehabilitated Kazekage Gaara S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Stun"]},
    {"id":206,"name":"Mizukage Mei S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Stun"]},
    {"id":207,"name":"Raikage Ay S","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD"]},
    {"id":208,"name":"Tsuchikage Ohnoki S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Increase",
    "Destroy DD",
    "Stun"]},
    {"id":209,"name":"Tobi S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Stun"]},
    {"id":210,"name":"Konan of the Rain S","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":211,"name":"Hoshigaki Kisame S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Chakra Drain",
    "Healer",
    "Ignore DD/Unable Reduce Damage"]},
    {"id":212,"name":"Hachibi Bee S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":213,"name":"Samehada Bee S","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain"]},
    {"id":214,"name":"White Snake Kabuto S","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Paralyze",
    "Stun"]},
    {"id":215,"name":"White Zetsu S","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Bleed",
    "Chakra Drain",
    "Counter",
    "Stun"]},
    {"id":216,"name":"Alliance Naruto","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Counter",
    "Stun"]},
    {"id":217,"name":"Alliance Sakura","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Bleed",
    "Healer"]},
    {"id":218,"name":"Alliance Sai","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":219,"name":"Alliance Kiba","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Stun"]},
    {"id":220,"name":"Alliance Shino","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Bleed",
    "Stun"]},
    {"id":221,"name":"Alliance Hinata","banned":"Yes","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain"]},
    {"id":222,"name":"Alliance Neji","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Ignore Friendly",
    "Stun"]},
    {"id":223,"name":"Alliance Lee","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer"]},
    {"id":224,"name":"Alliance Tenten","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Drain"]},
    {"id":225,"name":"Alliance Shikamaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive"]},
    {"id":226,"name":"Alliance Chouji","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Destroy DD",
    "Paralyze",
    "Stun"]},
    {"id":227,"name":"Alliance Ino","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter",
    "Unable to Reduce Damage/Invuln"]},
    {"id":228,"name":"Captain Kankuro","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Counter",
    "Stun",
    "Unable to Invuln"]},
    {"id":229,"name":"Zaji","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive"]},
    {"id":230,"name":"Omoi","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Ignore Friendly"]},
    {"id":231,"name":"Ittan","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":232,"name":"Captain Shizune","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive (IF in 1st Slot)",
    "Healer",
    "Stun (IF IN 3rd Slot)",
    "Unable to Reduce Damage/Invuln"]},
    {"id":233,"name":"Alliance Yugao","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Ignore DD",
    "Unable to Reduce Damage/Invuln"]},
    {"id":234,"name":"Io","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Healer",
    "Ignore DD",
    "Reflect"]},
    {"id":235,"name":"Commander Darui","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction"]},
    {"id":236,"name":"Atsui","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":237,"name":"Samui","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive"]},
    {"id":238,"name":"Commander Kitsuchi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":239,"name":"Karui","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":240,"name":"Mabui","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Support Character"]},
    {"id":241,"name":"Alliance Anko","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":242,"name":"Aburame Muta","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Support Character"]},
    {"id":243,"name":"Commander Kakashi","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Stun",
    "Unable to Invuln"]},
    {"id":244,"name":"Alliance Gai","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Stun"]},
    {"id":245,"name":"Monga","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Destroy DD"]},
    {"id":246,"name":"Maki","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Stun"]},
    {"id":247,"name":"Ruka","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Defensive",
    "Counter"]},
    {"id":248,"name":"Commander Gaara","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Paralyze",
    "Stun"]},
    {"id":249,"name":"Alliance Temari","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive/Defensive",
    "Reflect"]},
    {"id":250,"name":"Dodai","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive"]},
    {"id":251,"name":"Commander Mifune","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":252,"name":"Samurai Troops","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Support Character"]},
    {"id":253,"name":"Inuzuka Hana","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Defensive",
    "Healer",
    "Support Character"]},
    {"id":254,"name":"Edo Tensei Asuma","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive"]},
    {"id":255,"name":"Edo Tensei Dan","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Counter/Reflect",
    "Healer"]},
    {"id":256,"name":"Edo Tensei Hizashi","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Destroy DD"]},
    {"id":257,"name":"Edo Tensei Hayate","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Paralyze"]},
    {"id":258,"name":"Edo Tensei Shin","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Destory DD",
    "Healer"]},
    {"id":259,"name":"Edo Tensei Torune","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Ignore DD",
    "Unable to Reduce Damage"]},
    {"id":260,"name":"Edo Tensei Chiyo","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":261,"name":"Edo Tensei Daimaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive/Defensive",
    "Counter/Reflect"]},
    {"id":262,"name":"Edo Tensei Pakura","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction"]},
    {"id":263,"name":"Yashamaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":264,"name":"Edo Tensei Toroi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":265,"name":"Edo Tensei Fukai","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":266,"name":"Edo Tensei Ginkaku","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Stun"]},
    {"id":267,"name":"Edo Tensei Kinkaku","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Counter"]},
    {"id":268,"name":"Edo Tensei Kyubi Kinkaku","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Bleed",
    "Stun",
    "Unable to Reduce Damage/Invuln"]},
    {"id":269,"name":"Edo Tensei Chukichi","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Chakra Increase",
    "Unable to Reduce Damage/Invuln"]},
    {"id":270,"name":"Edo Tensei Haku","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Paralyze",
    "Stun"]},
    {"id":271,"name":"Edo Tensei Gari","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer",
    "Paralyze"]},
    {"id":272,"name":"Edo Tensei Chen","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":273,"name":"Edo Tensei Chukaku","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter",
    "Stun"]},
    {"id":274,"name":"Edo Tensei Hanzo","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":275,"name":"Edo Tensei Heiji","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Stun"]},
    {"id":276,"name":"Edo Tensei Tatewaki","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "Healer"]},
    {"id":277,"name":"Edo Tensei Yota","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Chakra Increase",
    "Paralyze",
    "Stun"]},
    {"id":278,"name":"Edo Tensei Tayuya","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Bleed",
    "Chakra Drain",
    "Counter",
    "Stun"]},
    {"id":279,"name":"Edo Tensei Kidomaru","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Destroy DD",
    "Stun"]},
    {"id":280,"name":"Edo Tensei Sakon and Ukon","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Defensive",
    "Stun"]},
    {"id":281,"name":"Edo Tensei Jirobo","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Unable to Reduce Damage/Invuln"]},
    {"id":282,"name":"Edo Tensei Kimimaro","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive"]},
    {"id":283,"name":"Edo Tensei Fuguki","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain (IF Samehada present)"]},
    {"id":284,"name":"Edo Tensei Ameyuri","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":285,"name":"Edo Tensei Jinin","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Unable to Reduce Damage/Invuln"]},
    {"id":286,"name":"Edo Tensei Jinpachi","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":287,"name":"Edo Tensei Kushimaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed"]},
    {"id":288,"name":"Edo Tensei Zabuza","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Bleed"]},
    {"id":289,"name":"Edo Tensei Mangetsu","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Drain",
    "Healer",
    "Stun",
    "Unable to Reduce Damage"]},
    {"id":290,"name":"Edo Tensei Sasori","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":291,"name":"Edo Tensei Deidara","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter"]},
    {"id":292,"name":"Edo Tensei Kakuzu","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer"]},
    {"id":293,"name":"Edo Tensei Nagato","banned":"Yes","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Chakra Drain",
    "Reflect",
    "Stun"]},
    {"id":294,"name":"Edo Tensei Itachi","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "Reflect"]},
    {"id":295,"name":"Kabutomaru","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Counter",
    "Healer",
    "Support Character"]},
    {"id":296,"name":"Edo Tensei Yugito","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD",
    "Unable to Reduce Damage/Invuln"]},
    {"id":297,"name":"Edo Tensei Yagura","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Destroy DD",
    "Unable to Reduce Damage/Invuln"]},
    {"id":298,"name":"Edo Tensei Roshi","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":299,"name":"Edo Tensei Han","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Increase",
    "Stun"]},
    {"id":300,"name":"Edo Tensei Utakata","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Stun"]},
    {"id":301,"name":"Edo Tensei Fuu","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Ignore DD and Damage Reduction"]},
    {"id":302,"name":"Commander Tobi","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Chakra Drain"]},
    {"id":303,"name":"Edo Tensei Sandaime Kazekage","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Bleed"]},
    {"id":304,"name":"Edo Tensei Yondaime Rasa","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive"]},
    {"id":305,"name":"Edo Tensei Nidaime Gengetsu","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter/Reflect"]},
    {"id":306,"name":"Edo Tensei Sandaime Ay","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer"]},
    {"id":307,"name":"Edo Tensei Nidaime Muu","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Bleed",
    "Healer"]},
    {"id":308,"name":"Edo Tensei Shodaime Hashirama","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Chakra Drain"]},
    {"id":309,"name":"Edo Tensei Nidaime Tobirama","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Healer"]},
    {"id":310,"name":"Edo Tensei Sandaime Hiruzen","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Bleed"]},
    {"id":311,"name":"Edo Tensei Yondaime Minato","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Unable to Reduce Damage"]},
    {"id":312,"name":"Edo Tensei Kyubi Minato","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":313,"name":"Alliance Tsunade","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Destroy DD",
    "Healer"]},
    {"id":314,"name":"Alliance Mei","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Defensive"]},
    {"id":315,"name":"Alliance Ay","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD",
    "Paralyze",
    "Unable to Reduce Damage"]},
    {"id":316,"name":"Alliance Ohnoki","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Bleed",
    "Chakra Increase",
    "Destroy DD",
    "Unable to Reduce Damage"]},
    {"id":317,"name":"Edo Tensei Madara","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Bleed"]},
    {"id":318,"name":"Uchiha Obito","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":319,"name":"Guruguru","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Counter",
    "Healer"]},
    {"id":320,"name":"Gedou Mazou","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Chakra Drain"]},
    {"id":321,"name":"Rehabilitated Karin","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":["Healer"]},
    {"id":322,"name":"Black Zetsu","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Ignore DD",
    "Reflect",
    "Unable to Reduce Damage/Invuln"]},
    {"id":323,"name":"Sage Kabuto","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Chakra Increase",
    "Healer"]},
    {"id":324,"name":"Sage Kurama Naruto","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive"]},
    {"id":325,"name":"Eternal Mangekyo Sasuke","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Paralyze"]},
    {"id":326,"name":"Rikudou Obito","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive"]},
    {"id":327,"name":"Rehabilitated Obito","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction"]},
    {"id":328,"name":"Rikudou Naruto","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive",
    "Counter"]},
    {"id":329,"name":"Rikudou Sasuke","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Stun"]},
    {"id":330,"name":"Otsutsuki Asura","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"Yes","skill_effects":["AoE Offensive",
    "Bleed",
    "Counter"]},
    {"id":331,"name":"Otsutsuki Indra","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"Yes","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Bleed",
    "Counter",
    "Healer",
    "Stun"]},
    {"id":332,"name":"Otsutsuki Hagoromo","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer",
    "Stun"]},
    {"id":333,"name":"Otsutsuki Hamura","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Unable to Reduce Damage/Invuln"]},
    {"id":334,"name":"Rikudou Hagoromo","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"Yes","skill_effects":["Affliction",
    "Counter",
    "Healer"]},
    {"id":335,"name":"Rikudou Hamura","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "Stun"]},
    {"id":336,"name":"Resurrected Madara","banned":"Yes","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Drain"]},
    {"id":337,"name":"Rikudou Madara","banned":"No","stun":"Yes","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Chakra Steal",
    "Stun"]},
    {"id":338,"name":"Otsutsuki Kaguya","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Increase",
    "Stun"]},
    {"id":339,"name":"Shukaku","banned":"Yes","stun":"Yes","chakra_drain":"Yes","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":[]},
    {"id":340,"name":"Matatabi","banned":"Yes","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":341,"name":"Isobu","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":342,"name":"Son Goku","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":[]},
    {"id":343,"name":"Kokuo","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":344,"name":"Saiken","banned":"Yes","stun":"No","chakra_drain":"Yes","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":345,"name":"Choumei","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"Yes","counter_reflect":"No","skill_effects":[]},
    {"id":346,"name":"Gyuki","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":347,"name":"Kurama","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":348,"name":"Juubi","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":349,"name":"Uzumaki Naruto TL","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":350,"name":"Hyuga Hinata TL","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Increase",
    "Destroy DD"]},
    {"id":351,"name":"Haruno Sakura TL","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"Yes","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Healer"]},
    {"id":352,"name":"Nara Shikamaru TL","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":353,"name":"Sai TL","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Unable to Reduce/Invuln"]},
    {"id":354,"name":"Otsutsuki Toneri","banned":"No","stun":"No","chakra_drain":"Yes","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Chakra Remove/Steal"]},
    {"id":355,"name":"Tenseigan Toneri","banned":"Yes","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive/Defensive",
    "Ignore DD"]},
    {"id":356,"name":"Uzumaki Boruto","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Paralyze",
    "Stun"]},
    {"id":357,"name":"Uchiha Sarada","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive",
    "Paralyze"]},
    {"id":358,"name":"Mitsuki","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Ignore DD",
    "Stun",
    "Unable to Reduce/Invuln"]},
    {"id":359,"name":"Metal Lee","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Destroy DD"]},
    {"id":360,"name":"Kaminarimon Denki","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Paralyze",
    "Stun"]},
    {"id":361,"name":"Yunio Iwabe","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["AoE Defensive"]},
    {"id":362,"name":"Nara Shikadai","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":363,"name":"Yamanka Inojin","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Unable to Reduce/Invuln"]},
    {"id":364,"name":"Akimichi Chocho","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Counter"]},
    {"id":365,"name":"Kakei Sumire","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Offensive/Defensive",
    "Chakra Remove/Steal"]},
    {"id":366,"name":"Suzumeno Namida","banned":"No","stun":"No","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Bleed",
    "Reflect"]},
    {"id":367,"name":"Izuno Wasabi","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Stun"]},
    {"id":368,"name":"Taketori Houki","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Affliction",
    "AoE Defensive"]},
    {"id":369,"name":"Kokubo Renga","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"Yes","skill_effects":["Healer",
    "Reflect"]},
    {"id":370,"name":"Kuroi Hako","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":[]},
    {"id":371,"name":"Onikuma Enko","banned":"No","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Stun"]},
    {"id":372,"name":"Goetsu Doushu","banned":"Yes","stun":"Yes","chakra_drain":"No","aoe":"Yes","heal":"No","counter_reflect":"No","skill_effects":["AoE Offensive",
    "Counter",
    "Stun"]},
    {"id":373,"name":"Itoi Tsuru","banned":"No","stun":"No","chakra_drain":"No","aoe":"No","heal":"No","counter_reflect":"No","skill_effects":["Chakra Increase"]}
])